version: '3.0'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: social-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123
  mysql:
    image: mysql:latest
    container_name: social-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=app