version: '3.0'
services:
  my-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123
  my-mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=app
  my-redis:
    image: redis
    ports:
      - 6379:6379